# Generated by Django 3.2.20 on 2024-02-17 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0146_alter_problemtestcase_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemtranslation',
            name='language',
            field=models.CharField(choices=[('ca', 'Catalan'), ('de', 'German'), ('en', 'English'), ('fr', 'French'), ('ja', 'Japanese'), ('ko', 'Korean'), ('ro', 'Romanian'), ('sr-latn', 'Serbian (Latin)'), ('tr', 'Turkish'), ('zh-hans', 'Simplified Chinese'), ('zh-hant', 'Traditional Chinese'), ('pl', 'Polish'), ('uk', 'Ukrainian')], max_length=7, verbose_name='language'),
        ),
    ]
